#!/usr/bin/env bash
set -euo pipefail

cat <<'EOF'
| S.No | Problem No. | Problem Name                                          | Category            | Interview Importance | Language             | Link                                                                                                                          |
| ---: | ----------: | ------------------------------------------------------ | -------------------- | --------------------: | --------------------- | ------------------------------------------------------------------------------------------------------------------------------ |
|    1 |          #1 | Two Sum                                                 | Hash Table            |                 10/10 | C++ / Java / Python3  | [0001-two-sum.cpp](./0001-two-sum/0001-two-sum.cpp)                                                                            |
|    2 |       #1480 | Running Sum of 1D Array                                 | Prefix Sum             |                  4/10 | C++ / Python3         | [1480-running-sum-of-1d-array.cpp](./1480-running-sum-of-1d-array/1480-running-sum-of-1d-array.cpp)                           |
|    3 |        #724 | Find Pivot Index                                        | Prefix Sum             |                  6/10 | C++ / Java / Python3  | [0724-find-pivot-index.cpp](./0724-find-pivot-index/0724-find-pivot-index.cpp)                                                |
|    4 |       #1929 | Concatenation of Array                                  | Array                  |                  3/10 | C++ / Java / Python3  | [1929-concatenation-of-array.cpp](./1929-concatenation-of-array/1929-concatenation-of-array.cpp)                              |
|    5 |       #1920 | Build Array from Permutation                            | Array                  |                  3/10 | C++ / Java / Python3  | [1920-build-array-from-permutation.cpp](./1920-build-array-from-permutation/1920-build-array-from-permutation.cpp)            |
|    6 |       #1470 | Shuffle the Array                                       | Array                  |                  3/10 | C++ / Java / Python3  | [1470-shuffle-the-array.cpp](./1470-shuffle-the-array/1470-shuffle-the-array.cpp)                                             |
|    7 |       #2011 | Final Value of Variable After Performing Operations      | Simulation             |                  2/10 | C++ / Java / Python3  | [2011-final-value-of-variable-after-performing-operations.cpp](./2011-final-value-of-variable-after-performing-operations/2011-final-value-of-variable-after-performing-operations.cpp) |
|    8 |       #1431 | Kids With the Greatest Number of Candies                 | Array                  |                  3/10 | C++ / Java / Python3  | [1431-kids-with-the-greatest-number-of-candies.cpp](./1431-kids-with-the-greatest-number-of-candies/1431-kids-with-the-greatest-number-of-candies.cpp) |
|    9 |       #1672 | Richest Customer Wealth                                 | Matrix                 |                  3/10 | C++ / Java / Python3  | [1672-richest-customer-wealth.cpp](./1672-richest-customer-wealth/1672-richest-customer-wealth.cpp)                           |
|   10 |        #412 | Fizz Buzz                                               | Simulation             |                  5/10 | C++ / Java / Python3  | [0412-fizz-buzz.cpp](./0412-fizz-buzz/0412-fizz-buzz.cpp)                                                                      |
|   11 |       #1512 | Number of Good Pairs                                    | Counting               |                  4/10 | C++ / Java / Python3  | [1512-number-of-good-pairs.cpp](./1512-number-of-good-pairs/1512-number-of-good-pairs.cpp)                                    |
|   12 |       #1365 | How Many Numbers Are Smaller Than the Current Number     | Counting Sort          |                  4/10 | C++ / Java / Python3  | [1365-how-many-numbers-are-smaller-than-the-current-number.cpp](./1365-how-many-numbers-are-smaller-than-the-current-number/1365-how-many-numbers-are-smaller-than-the-current-number.cpp) |
|   13 |       #1295 | Find Numbers with Even Number of Digits                 | Math                   |                  4/10 | C++ / Java / Python3  | [1295-find-numbers-with-even-number-of-digits.cpp](./1295-find-numbers-with-even-number-of-digits/1295-find-numbers-with-even-number-of-digits.cpp) |
|   14 |        #485 | Max Consecutive Ones                                    | Array                  |                  6/10 | C++ / Java / Python3  | [0485-max-consecutive-ones.cpp](./0485-max-consecutive-ones/0485-max-consecutive-ones.cpp)                                    |
|   15 |        #977 | Squares of a Sorted Array                                | Two Pointers          |                  7/10 | C++ / Java / Python3  | [0977-squares-of-a-sorted-array.cpp](./0977-squares-of-a-sorted-array/0977-squares-of-a-sorted-array.cpp)                     |
|   16 |        #283 | Move Zeroes                                             | Two Pointers          |                  8/10 | C++ / Java / Python3  | [0283-move-zeroes.cpp](./0283-move-zeroes/0283-move-zeroes.cpp)                                                                |
|   17 |         #26 | Remove Duplicates from Sorted Array                     | Two Pointers          |                  8/10 | C++ / Java / Python3  | [0026-remove-duplicates-from-sorted-array.cpp](./0026-remove-duplicates-from-sorted-array/0026-remove-duplicates-from-sorted-array.cpp) |
|   18 |         #27 | Remove Element                                          | Two Pointers          |                  6/10 | C++ / Java / Python3  | [0027-remove-element.cpp](./0027-remove-element/0027-remove-element.cpp)                                                       |
|   19 |         #88 | Merge Sorted Array                                      | Two Pointers          |                  8/10 | C++ / Java / Python3  | [0088-merge-sorted-array.cpp](./0088-merge-sorted-array/0088-merge-sorted-array.cpp)                                           |
|   20 |        #125 | Valid Palindrome                                        | Two Pointers          |                  9/10 | C++ / Java / Python3  | [0125-valid-palindrome.cpp](./0125-valid-palindrome/0125-valid-palindrome.cpp)                                                 |
|   21 |        #344 | Reverse String                                          | Two Pointers          |                  6/10 | C++ / Java / Python3  | [0344-reverse-string.cpp](./0344-reverse-string/0344-reverse-string.cpp)                                                       |
|   22 |        #392 | Is Subsequence                                          | Two Pointers          |                  6/10 | C++ / Java / Python3  | [0392-is-subsequence.cpp](./0392-is-subsequence/0392-is-subsequence.cpp)                                                       |
|   23 |        #680 | Valid Palindrome II                                     | Greedy                 |                  8/10 | C++ / Java / Python3  | [0680-valid-palindrome-ii.cpp](./0680-valid-palindrome-ii/0680-valid-palindrome-ii.cpp)                                       |
|   24 |         #11 | Container With Most Water                               | Two Pointers          |                 10/10 | C++ / Java / Python3  | [0011-container-with-most-water.cpp](./0011-container-with-most-water/0011-container-with-most-water.cpp)                     |
|   25 |         #42 | Trapping Rain Water                                     | Two Pointers          |                 10/10 | C++ / Java / Python3  | [0042-trapping-rain-water.cpp](./0042-trapping-rain-water/0042-trapping-rain-water.cpp)                                        |
|   26 |        #643 | Maximum Average Subarray I                              | Sliding Window        |                  6/10 | C++ / Java / Python3  | [0643-maximum-average-subarray-i.cpp](./0643-maximum-average-subarray-i/0643-maximum-average-subarray-i.cpp)                  |
|   27 |       #1456 | Maximum Number of Vowels in a Substring of Given Length  | Sliding Window        |                  7/10 | C++ / Java / Python3  | [1456-maximum-number-of-vowels-in-a-substring-of-given-length.cpp](./1456-maximum-number-of-vowels-in-a-substring-of-given-length/1456-maximum-number-of-vowels-in-a-substring-of-given-length.cpp) |
|   28 |        #219 | Contains Duplicate II                                   | Sliding Window        |                  7/10 | C++ / Java / Python3  | [0219-contains-duplicate-ii.cpp](./0219-contains-duplicate-ii/0219-contains-duplicate-ii.cpp)                                  |
|   29 |          #3 | Longest Substring Without Repeating Characters          | Sliding Window        |                 10/10 | C++ / Java / Python3  | [0003-longest-substring-without-repeating-characters.cpp](./0003-longest-substring-without-repeating-characters/0003-longest-substring-without-repeating-characters.cpp) |
|   30 |        #209 | Minimum Size Subarray Sum                               | Sliding Window        |                  9/10 | C++ / Java / Python3  | [0209-minimum-size-subarray-sum.cpp](./0209-minimum-size-subarray-sum/0209-minimum-size-subarray-sum.cpp)                     |
|   31 |        #424 | Longest Repeating Character Replacement                 | Sliding Window        |                 10/10 | C++ / Java / Python3  | [0424-longest-repeating-character-replacement.cpp](./0424-longest-repeating-character-replacement/0424-longest-repeating-character-replacement.cpp) |
|   32 |        #567 | Permutation in String                                   | Sliding Window        |                 10/10 | C++ / Java / Python3  | [0567-permutation-in-string.cpp](./0567-permutation-in-string/0567-permutation-in-string.cpp)                                 |
|   33 |        #438 | Find All Anagrams in a String                           | Sliding Window        |                 10/10 | C++ / Java / Python3  | [0438-find-all-anagrams-in-a-string.cpp](./0438-find-all-anagrams-in-a-string/0438-find-all-anagrams-in-a-string.cpp)          |
|   34 |         #76 | Minimum Window Substring                                | Sliding Window        |                 10/10 | C++ / Java / Python3  | [0076-minimum-window-substring.cpp](./0076-minimum-window-substring/0076-minimum-window-substring.cpp)                        |
|   35 |        #239 | Sliding Window Maximum                                  | Sliding Window        |                 10/10 | C++ / Java / Python3  | [0239-sliding-window-maximum.cpp](./0239-sliding-window-maximum/0239-sliding-window-maximum.cpp)                              |
|   36 |        #217 | Contains Duplicate                                      | Hash Table            |                  9/10 | C++ / Java / Python3  | [0217-contains-duplicate.cpp](./0217-contains-duplicate/0217-contains-duplicate.cpp)                                           |
|   37 |        #242 | Valid Anagram                                           | Hash Table            |                 10/10 | C++ / Java / Python3  | [0242-valid-anagram.cpp](./0242-valid-anagram/0242-valid-anagram.cpp)                                                          |
EOF
